name: Save Environment Variables as Artifact

on: [push, pull_request]

jobs:
  save-env:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Save environment variables to file
      run: |
        echo "Saving environment variables..."
        # Print all environment variables to a file
        printenv > env_variables.txt
        # Display the content of the file for debugging purposes
        cat env_variables.txt

    - name: Upload environment variables as artifact
      uses: actions/upload-artifact@v3
      with:
        name: env-variables
        path: env_variables.txt
