name: Save Secrets and Environment Variables

on: [push, pull_request]

jobs:
  save-env-and-secrets:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Read environment variables and secrets
      run: |
        echo "Saving environment variables and secrets to file..."

        # Read repository environment variables
        echo "APP_ID=${{ vars.XD }}" >> env_and_secrets.txt

        # Read secrets
        echo "API_KEY=${{ secrets.API_KEY }}" >> env_and_secrets.txt
        echo "DOES_NOT_EXIST=${{ secrets.DOES_NOT_EXIST }}" >> env_and_secrets.txt

    - name: Upload environment variables and secrets as artifact
      uses: actions/upload-artifact@v3
      with:
        name: env-and-secrets
        path: env_and_secrets.txt
